logging:
  level:
    net:
      milanvit: debug
    io:
      netty: debug
      reactor: debug
    org:
      springframework:
        data: trace
    reactor:
      core: trace
      util: trace
management:
  endpoints:
    web:
      exposure:
        include: ["conditions", "env", "health", "info", "metrics"]
  endpoint:
    health:
      show-details: always
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
spring:
  devtools:
    remote:
      secret: learning-spring-boot
  main:
    allow-bean-definition-overriding: true